import streamlit as st

def render_executive_summary(engine):
    st.header("Executive Summary & Recommendations")
    
    st.info("Generated by Advanced Analytics Engine — February 2026")
    
    with st.spinner("Generating Dynamic Insights..."):
        # Fetch dynamic stats
        anomaly_df = engine.fetch_metric('anomaly_detection')
        funnel_df = engine.fetch_metric('view_to_cart_funnel')
        cart_df = engine.fetch_metric('cart_abandonment_rate')
        weekend_df = engine.fetch_metric('weekend_degradation')
        ttf_df = engine.fetch_metric('time_to_first_purchase')
        basket_df = engine.fetch_metric('market_basket_pairs')
        
        # Calculate dynamic insights
        max_anomaly_drop = anomaly_df.iloc[0]['drop_percentage'] if not anomaly_df.empty else 0
        worst_day = anomaly_df.iloc[0]['act_date'].date() if not anomaly_df.empty else "No anomalies"
        
        avg_abandonment = cart_df.iloc[0]['avg_historical_abandonment'] if not cart_df.empty else 0
        v2c = funnel_df.iloc[0]['view_to_cart_rate'] if not funnel_df.empty else 0
        
        top_pair_a = basket_df.iloc[0]['product_a'] if not basket_df.empty else "N/A"
        top_pair_b = basket_df.iloc[0]['product_b'] if not basket_df.empty else "N/A"
        
        # Fast buyers is dynamically calculated in SQL to prevent Pandas aggregations
        fast_buyers = ttf_df.iloc[0]['fast_buyers_pct'] if not ttf_df.empty else 0
        
    st.markdown(f"""
    ### 1. Key Findings
    
    * **Robust Base Conversion:** Our `view_to_cart_funnel` indicates users are exhibiting a **{v2c:.1f}%** View-to-Cart intent.
    * **Temporal Discrepancy:** The models expose a systemic drop in *Revenue Per Session* during weekends compared to weekdays. 
    * **Cart Vulnerability:** Carts are routinely abandoned. The `cart_abandonment_rate` averages **{avg_abandonment:.2f}%** historically.
    
    ---
    
    ### 2. Identified Bottlenecks
    
    1. **The Weekend Trough:** High volume, low intent. Traffic spikes slightly on weekends, but `cart_to_purchase_rate` plummets. 
    2. **Abandoned Carts:** Our data shows severe historical abandonment (avg {avg_abandonment:.1f}%). 
    3. **First-Purchase Hesitation:** Nearly **{fast_buyers:.1f}%** of buyers purchase within their first 60 minutes. If they don't buy immediately, the probability of conversion drops drastically.
    
    ---
    
    ### 3. Actionable Optimizations (Next 30 Days)
    
    > **Recommendation 1: Deploy 'Flash Discounts' During Weekend Anomaly Zones**
    > Counteract the weekend degradation. Our anomaly detection engine caught a maximum drop of **{max_anomaly_drop}%** on **{worst_day}**. Implement automated discounting for weekend lulls.
    
    > **Recommendation 2: Aggressive Cart Recovery Email Cadence**
    > Since abandonment hovers at **{avg_abandonment:.1f}%**, implement an automated email trigger 45 minutes after abandonment. The first hour is critical.
    
    > **Recommendation 3: Up-sell '{top_pair_a}' and '{top_pair_b}'**
    > Hardcode '{top_pair_a}' + '{top_pair_b}' directly into the checkout UI as "Frequently Bought Together" to artificially inflate the average order value.
    
    """)

